### ISSUE TITLE
press "open editor", but no "openpose editor" appear:

### ISSUE THREAD

**Issue by xueqing0622** [space-nuko/ComfyUI-OpenPose-Editor#8]
press "open editor", but no "openpose editor" appear:
Press F12:show error:

openpose.js:625 
 Uncaught TypeError: Cannot read properties of null (reading 'tl')
    at openpose.js:625:48
    at Array.map (<anonymous>)
    at openpose.js:625:28
    at Array.map (<anonymous>)
    at OpenPosePanel.serializeJSON (openpose.js:623:34)
    at OpenPosePanel.saveToNode (openpose.js:531:49)
    at OpenPosePanel.setPose (openpose.js:332:14)
    at new OpenPosePanel (openpose.js:209:18)
    at Object.callback (openpose.js:714:38)
    at litegraph.core.js:10002:35
(匿名)	@	openpose.js:625
(匿名)	@	openpose.js:625
serializeJSON	@	openpose.js:623
saveToNode	@	openpose.js:531
setPose	@	openpose.js:332
OpenPosePanel	@	openpose.js:209
(匿名)	@	openpose.js:714
(匿名)	@	litegraph.core.js:10002
setTimeout(异步)		
LGraphCanvas.processNodeWidgets	@	litegraph.core.js:10001
LGraphCanvas.processNodeWidgets	@	bilboxContextMenuEnhance.js:201
LGraphCanvas.processMouseDown	@	litegraph.core.js:6072
LGraphCanvas.processMouseDown	@	app.js:846

**Comment by markawonge** [comment]
Same problem, press"open editor" but no response.

OS: Ubuntu 22.04.3 LTS + ROCm 5.7
GPU: AMD RX7900XT
![截屏2023-12-05 17 20 10](https://github.com/space-nuko/ComfyUI-OpenPose-Editor/assets/9694641/07102cdc-5720-4ac0-8b24-739111d00a93)

**Comment by sacredbone** [comment]
Sane here, tried reinstall and everything. Doesn't work anymore.

![bug](https://github.com/space-nuko/ComfyUI-OpenPose-Editor/assets/107143108/bfbb4ce2-21e0-4222-8af5-7defc3aacfe6)

**Comment by DENG-XC** [comment]
> Same problem, press"open editor" but no response.
> 
> OS: Ubuntu 22.04.3 LTS + ROCm 5.7 GPU: AMD RX7900XT ![截屏2023-12-05 17 20 10](https://private-user-images.githubusercontent.com/9694641/287987617-07102cdc-5720-4ac0-8b24-739111d00a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTM0OTIsIm5iZiI6MTcwNTM5MzE5MiwicGF0aCI6Ii85Njk0NjQxLzI4Nzk4NzYxNy0wNzEwMmNkYy01NzIwLTRhYzAtOGIyNC03MzkxMTFkMDBhOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDgxOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIwMWMyNWI3NWRlM2MwMjU4MGZkN2JjMGQyMzQ0NjU2NWIzYjAyODdhYjY1YWEzNWNmMjJkNDVmZGIxNzUxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NUPpJ2-SGwoAPi_yrl540aZMh_GUhB7QWJNEb7KqjrI)

Hi, there, I have same problem as you, did you fix this problem?

**Comment by sacredbone** [comment]
It has something to do with getting not getting the inital data correctly. Still waiting for a solution as well. :/

**Comment by rollingcookies** [comment]
Similarly, the OpenPose editor does not want to work. Nothing happens when you click on the button [Open Editor] in freshly added node. And when you load Workflow with this node, the editor opens, but the poses in it are not editable - they have no circles in the places where the bones are attached.

**Comment by dakezuo** [comment]
I have same problem as you

**Comment by Willber1995** [comment]
same here

**Comment by sacredbone** [comment]
Since this issue is now 9 months old, if you have this issue check out this node:
https://github.com/whmc76/ComfyUI-Openpose-Editor-Plus

**Comment by Willber1995** [comment]
我解决了这个问题了，我是从bilibili下载的秋叶整合包，换成官方包装这个插件就能正常使用了
I have solved this problem by replaced the aaaki Integration Package into official package. This plugin can be used normally

**Comment by Whatsk** [comment]
> 我解决了这个问题了，我是从bilibili下载的秋叶整合包，换成官方包装这个插件就能正常使用了 我通过将 aaaki 集成包替换为官方包解决了这个问题。 该插件可以正常使用

前面有个评论说了是openpose.js的问题,整合包加了前置代理, 但是不懂代码不知道怎么改.

**Comment by hlsbd** [comment]
> > 我解决了这个问题了，我是从bilibili下载的秋叶整合包，换成官方包装这个插件就能正常使用了 我通过将 aaaki 集成包替换为官方包解决了这个问题。该插件可以正常使用
> 
> 前面有个评论说了是openpose.js的问题，整合包加了前置代理， 但是不懂代码不知道怎么改.

把选项卡里的代理服务器全开

**Comment by JakeSSRN** [comment]
I'm having this issue as well.

**Comment by metamountain** [comment]
use dw pose instead. it seems better anyway...That node can be obtained by installing Fannovel16's ComfyUI's ControlNet Auxiliary Preprocessors custom node.

**Comment by Delerium** [comment]
> use dw pose instead. it seems better anyway...That node can be obtained by installing Fannovel16's ComfyUI's ControlNet Auxiliary Preprocessors custom node.

dw pose doesn't have a pose editor in it, so how is that even a solution?

**Comment by hajo456** [comment]
Try this way:
https://zhuyu1997.github.io/open-pose-editor/

It works very well!

**Comment by andreszs** [comment]
This crash, and the other old OpenPose Editor errors, were fixed in the new replacement:

<a href="https://www.andreszsogon.com/building-a-multi-character-comfyui-workflow-with-area-conditioning-openpose-control-and-style-layering/">
  <img width="1400" height="752" alt="ComfyUI OpenPose Studio editor" src="https://github.com/user-attachments/assets/a5c4c24f-6205-4982-8007-98e65c494fd7" />
</a>

## ComfyUI OpenPose Studio
https://github.com/andreszs/ComfyUI-OpenPose-Studio

I rebuilt it from scratch to replace this obsolete extension.

Main advantages:

- 100% compatible with old OpenPose Editor JSON
- visual pose editing directly in ComfyUI
- pose gallery with previews
- pose collections and better pose organization
- JSON import/export
- cleaner and more reliable editor UX

> It is still new and **not in ComfyUI Manager yet**, so please give it a **star** if you want to help it gain visibility and get listed there.

I also posted a workflow article showing it in action:
https://www.andreszsogon.com/building-a-multi-character-comfyui-workflow-with-area-conditioning-openpose-control-and-style-layering/

If you are here because the old editor throws errors or fails to open, this is the replacement you want.
